### ISSUE TITLE
Hello from React Storybook

### ISSUE THREAD

**Issue by arunoda** [bhauman/devcards#102]
Hi @bhauman and the team.

I have recently worked on a similar tool (only works for React now) in JavaScript. 
See: https://github.com/kadirahq/react-storybook/

A few people have showed me your project and this looks pretty cool.
I had a look at this and looking to get some ideas from this projects.

Here's my initial impressions: https://github.com/kadirahq/react-storybook/issues/19

Looking forward for any suggestions and I would really like to learn from you guys.

Thanks.

**Comment by wildwestrom** [comment]
Is there any reason to use this tool over storybook?

https://shaolang.github.io/posts/2021-02-14-storybook.js-with-shadow-cljs/
