### ISSUE TITLE
Markdown tables don't render

### ISSUE THREAD

**Issue by den1k** [bhauman/devcards#115]
I tried the following in showdown and it works:

```
  | Tables        | Are           | Cool  |
  | ------------- |:-------------:| -----:|
  | **col 3 is**  | right-aligned | $1600 |
```

It also works in github markdown:

  | Tables        | Are           | Cool  |
  | ------------- |:-------------:| -----:|
  | **col 3 is**  | right-aligned | $1600 |

However, this devcard

```
(defcard-doc
  "#Tables don't work?

  | Tables        | Are           | Cool  |
  | ------------- |:-------------:| -----:|
  | **col 3 is**  | right-aligned | $1600 |")
```
looks like this:

![image](https://cloud.githubusercontent.com/assets/4651810/20023805/c38a4ad8-a2b8-11e6-80a6-9993a71bb83e.png)

**Comment by bhauman** [comment]
fixed this by using marked, as the showdown on cljsjs didn't render tables
