### ISSUE TITLE
Aggregate Test Results?

### ISSUE THREAD

**Issue by brosenan** [bhauman/devcards#124]
Is there a way to show an aggregation of all test results?
What I want is an easy way to see, as I go through the phases of TDD (red/green/refactor) whether I am "green" or "red", i.e., is there a failing test right now somewhere in my inspected code-base.

Out of the box I see aggregation only on the `deftest` level, which might be too restrictive.
Is there an easy way to get this information at the top of each page?  Or on the index page?

Thanks,
Boaz

**Comment by sp3ctum** [comment]
I'm kind of interested in this, but I'm looking for a way to get my tests run from the command line and possibly on Travis CI. I am under the impression that it's possible with clojurescript tests, but the reference solutions I've seen seem a bit hacky.

**Comment by brosenan** [comment]
[this blog post](https://8thlight.com/blog/eric-smith/2016/10/05/a-testable-clojurescript-setup.html) walks you through a nice setup that includes both the online feedback using devcards on a real browser, and also gives you an ability to run tests from the command line on PhantomJS for CI.
This should work on Travis because [Travis supports PhantomJS](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS).

**Comment by sp3ctum** [comment]
Yes, that setup seems quite nice. My issue is it's a lot of work and a lot
to maintain and remember, and also to do again on my next you project..

I'm not saying it's something that should be done in figwheel, but I would
very much like it if there was some de facto way of doing it.

Thanks for the link though, I might try and incorporate it into my project
at some point.

**Comment by brosenan** [comment]
Please see [this project](https://github.com/brosenan/cljs-dev-env) I created for exactly this purpose.
It's a template project you can clone and modify to your needs, and it has the setup described in the post.
One could take this one step forward and create a lein template out of it...

**Comment by bhauman** [comment]
I highly recommend https://github.com/bhauman/cljs-test-display for project testing.
