### ISSUE TITLE
Using with figwheel.main

### ISSUE THREAD

**Issue by ychakiris** [bhauman/devcards#143]
I haven't tried it yet but I assume this will work with figwheel.main if we put the right dependencies in (e.g. taking the dependencies our ot the current `project.clj` file).

**Comment by bhauman** [comment]
You just need to add `:devcards true` to your clojurescript compiler options.

```clojure
{:main example.core
  :asset-path ....
  :devcards true}
```

**Comment by tlamr** [comment]
ah! brilliant! Works perfectly :)

Thanks!
