### ISSUE TITLE
reagent devcard

### ISSUE THREAD

**Issue by dagda1** [bhauman/devcards#16]
Does devcards work with reagent and if not, could somebody give me a rough idea as to what would be involved in creating a base card that works with reagent.

**Comment by bhauman** [comment]
Reagent now works with devcards.

**Comment by whodidthis** [comment]
Not sure if possible, but would be interested if someone has an idea on how to use with [re-frame](https://github.com/Day8/re-frame)

**Comment by bhauman** [comment]
@whodidthis it should work for the individual reagent components right?

**Comment by whodidthis** [comment]
They work great, re-frame just has this predefined app-db atom that might make devcards impossible.

Out of interest, is there anything interesting to the atom you can feed to `defcard` when it comes to reagent? Is there any difference between
```clojure
(defonce my-atom (reagent.core/atom {}))

(defcard my-card
  (dc/reagent [my-component my-atom]))
```
and
```clojure
(defcard my-card
  (dc/reagent my-component)
  my-atom)
```
Or is it just as a backup if people want to use om-cards and reagent-cards in a similar way.

**Comment by bhauman** [comment]
You get the history and data inspection with the second method.

**Comment by whodidthis** [comment]
Cool, didn't realize
