### ISSUE TITLE
Bootstrap styles override personal

### ISSUE THREAD

**Issue by whodidthis** [bhauman/devcards#18]
This is pretty random since you dont necessarily need to keep using the bootstrap stuff with devcards, but I was wondering if it would be better to use some namespaced framework like purecss to create the bundled interface. Just to get a works out of the box experience when people create components on devcards.

**Comment by justiniac** [comment]
What's the current status on this, considering the recent changes? Still needing help?

**Comment by bhauman** [comment]
Bootstrap is no longer used or needed :) Thanks for the offer.

@justiniac if you would like to help please take the new devcards for a drive
