### ISSUE TITLE
Showing cards for non-core files?

### ISSUE THREAD

**Issue by mathpunk** [bhauman/devcards#21]
I'm trying out devcards, and something surprised me. When I look at `http://localhost:3449/devcards/index.html` it includes a link for `projectname_devcards.core` and projectname.core. I expected that when I created a new file, like `module.cljs`, and included the same devcard dependencies as I did in the core file, that there would be a new link for `projectname.module`, but that was not the case. I thought the files that figwheel checks might be in `project.clj` but no such luck. Can a note be added to the documentation on how to get devcards for namespaces other than core to show up?

**Comment by bhauman** [comment]
Are you using the devcards template?

**Comment by mathpunk** [comment]
That's right.

**Comment by bhauman** [comment]
Tom I'm pretty sure this is happening because you are not requiring the namespace that the new cards are in.  Figwheel only reloads files that have been required.

**Comment by mathpunk** [comment]
That seems to be precisely what is happening. It was not obvious that I'd need to touch `devcards_src/core.cljs` unless I was creating new *kinds* of cards. 

I've tried to clarify that in the template. Pull request incoming. 

PS -- I love this library! It is especially good for someone like me who understands functional programming okay but is bewildered by how many moving parts an HTML document has.
