### ISSUE TITLE
Test cards only run the last test if the whole card is defined as a "let"

### ISSUE THREAD

**Issue by emanchado** [bhauman/devcards#22]
It seems that defining a test card as a let block makes the card only execute the last test. At first I didn't realise that each test should have a row with results (I'm just getting started with devcards), so I didn't even realise that my tests were failing! For someone more familiar with devcards is less of a problem, but still...

Example code:

```clojure
(defcard bug-testcase
  (dc/test-card
   "Test case for let bug in devcard's test card"
   (let [expected 1]
     (dc/are= expected 0)
     (dc/are= expected 1))))
```

I imagine this is a bug and not expected behaviour, and I hope it's possible to fix :-)

**Comment by bhauman** [comment]
If you return a list of tests this will work correctly.

I'm probably going to be redoing most of this over the next month.  And try to use cljs.test for testing. Devcards is going to undergo a big make over hopefully :)

**Comment by bhauman** [comment]
And a simplification as well.

**Comment by bhauman** [comment]
This has been addressed with the latest release of devcards which now uses cljs.test!
