### ISSUE TITLE
Run 'lein figwheel' and then open localhost:3449/devcards.html in your browser = 404

### ISSUE THREAD

**Issue by justiniac** [bhauman/devcards#23]
Minor issue: after a successful `lein new devcards myapp` the prompt says:
`Run 'lein figwheel' and then open localhost:3449/devcards.html in your browser.`
Doing so will shout a 404.

`localhost:3449` works fine, though.

**Comment by bhauman** [comment]
Thats weird it should work.  hmmm.

**Comment by bhauman** [comment]
This is actually in the devcards-template.  Maybe I haven't deployed the latest code.

**Comment by bhauman** [comment]
Maybe you are using an old template.  Please get rid of the devcards-template in your maven repo and try again.  Maybe you need http://localhost:3449/devcards.html

**Comment by justiniac** [comment]
duh, I was in my plain figwheel term window :o/ all good in devcards!
Sorry for bothering you.

**Comment by bhauman** [comment]
No worries!!!

**Comment by bhauman** [comment]
Really glad you are giving it a try. Please feel free to report stuff.
