### ISSUE TITLE
Factoring out Markdown source

### ISSUE THREAD

**Issue by arichiardi** [bhauman/devcards#40]
Hi Bruce,
I was working with ```devcards``` and found out that it would be great to have a Markdown component for ```ReactJS```/```reagent```, so I went ahead and factored out your code into [this](https://github.com/arichiardi/reactive-markdown) !
Now, I don't know which licensing you are using, but I figured I might just ask if you are interested in either maintaining something like this, or agree to me putting it in my works...don't know, at the end of the day is your (very good) work.
Have a look at the (very rough and in progress) code and let me know ok?
Thanks!

**Comment by arichiardi** [comment]
Sorry I pushed my changes now. You can have a look.

**Comment by bhauman** [comment]
Man that is fine with me. It would just be nice if the readme / code
mentions where it came from.

**Comment by arichiardi** [comment]
Well of course, that is the minimum I can do :+1:

**Comment by bhauman** [comment]
:)
