### ISSUE TITLE
lein template doesn't work when using the name `devcards`

### ISSUE THREAD

**Issue by orlin** [bhauman/devcards#41]
Following the "Super Quick Start" instructions from the readme, I generated a devcards project using `Leiningen 2.5.3 on Java 1.8.0_25`.  Started `lein figwheel` and opened the page.  The `cards.html` page is blank.  The `index.html` page is also blank and points to a non-existing `/js/compiled/devcards.js`script - I'm guessing the latter is intentional (my project's home page, the project being "devcards" in this case).

I cloned devcards itself and that worked fine, so the problem must be in the leiningen template.

**Comment by orlin** [comment]
Ok, maybe the issue is just with `lein new devcards devcards`.  I tried a project named differently and that works fine.  Then I tried the generated "devcards" project again and, again, it didn't work.  So this isn't a blocking issue.  Thanks for the cool project.

**Comment by bhauman** [comment]
@orlin Yeah this is a problem.  `lein new devcards devcards` creates a new `devcards.core` ns which could cause the system to think that it has already required the devcards code.   

I'm sure we can make a warning if someone attempts this.  You interested adding such a warning?

**Comment by orlin** [comment]
I'm not familiar enough with leiningen so someone else could probably add this more easily.  Maybe just a mention in the readme is enough?  In my mind though, devcards don't belong mixed with the `app.core` (or `lib.core`) code or in the app namespace at all.  Unless the project is a project for playing with / developing devcards, and even devcards itself puts its cards elsewhere, i.e. devdemos.  What's the reason for having the `devdemos` in `example_src` rather than just `src`?

Here is what I ended up using:
`lein new devcards demos && mv demos/* . && rmdir demos`.  It seems that devcards / `cards.html` can naturally be part of the potential demos (maybe `index.html` becomes `demos.html`), showing what a given project does.  If you think a separate namespace is good, maybe pick the most semantically suitable name for devcards to go in, another one I considered was 'proto'.  This would probably stick around to be the usual place one finds devcards in, it would also allow to generate a project by giving it just the project name.

So, one solution would be to change where devcards go - some other (?) fixed place, for a more permanent home.  Currently, with `lein new devcards demos`, one ends up having to manually rename the app in `project.clj` and create the app namespace by hand.  Can `leiningen new ...` take 2 parameters (for separate app and cards namespaces), or apply a template to an existing project (adding devcards ability)?

**Comment by bhauman** [comment]
this has been fixed
