### ISSUE TITLE
mkdn-pprint-source fails with "No reader function for tag js"

### ISSUE THREAD

**Issue by frankhale** [bhauman/devcards#45]
Armed with this information, lifted from: http://rigsomelight.com/devcards/#!/devdemos.source_code_display

> Because the mkdn-pprint-source makes use of the cljs.repl to get the source code for an object, we can use it to display the source code for any object accessible to our current namespace.

I want to use mkdn-pprint-source to print the following source code. The function is defined in the same file I am trying to display it in. I am using defcard-doc.

```clojure
(defn create-player []
  (reset! player-state
    (YT.Player. "player" #js { :videoId "wrMBe5cyNKA"
                               :playerVars #js { :autoplay 0 :autohide 1 }})))
```

Here is my defcard-doc declaration:

```clojure
(defcard-doc
  (dc/mkdn-pprint-source create-player))
```

Here is the error verbatim:

```
Compile Error
clojure.lang.ExceptionInfo : failed compiling file:src\toby_devcards\core.cljs
clojure.lang.ExceptionInfo : No reader function for tag js at line 119 src\toby_devcards\core.cljs
clojure.lang.ExceptionInfo : No reader function for tag js
Error on file src\toby_devcards\core.cljs, line 119, column 3
```

Am I doing something wrong (I can get other simple functions to print in the devcard-doc)?

**Comment by bhauman** [comment]
Good question.
@pkobrien??

**Comment by frankhale** [comment]
The problem seems to be that It doesn't like #js

**Comment by frankhale** [comment]
As an interim fix I'm just going to switch from #js to clj->js as mkdn-pprint-source doesn't have a problem with that.

**Comment by fdserr** [comment]
Got `#` caught by the reader even in comments, bah ^^ Nice macro anyway, wish it'd take `def` and `defonce` too.

**Comment by pkobrien** [comment]
I'm not sure what is causing that problem. As you know, all the code is doing is leveraging `source-fn` from cljs.repl, so ultimately this should be reported as a cljs bug. The code is here:

https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/repl.cljc#L1202-L1222

And we're using `source-fn` in the Devcards macro pretty much the same way that the REPL `source` macro uses it here:

https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/repl.cljc#L1235-L1242

So if someone could make a simple test case and report it as a cljs bug that would be great. Here is a similar bug that was recently fixed:

http://dev.clojure.org/jira/browse/CLJS-1261

Could also check with dnolen to see if this is a known issue.

**Comment by frankhale** [comment]
Thank you @pkobrien for this information. I'll report it to the ClojureScript folks.
