### ISSUE TITLE
dom-node macro does not update on atom change

### ISSUE THREAD

**Issue by fdserr** [bhauman/devcards#48]
The following card shows the issue (include `dom-node` in the devcards `:require-macros` and paste-in):

``` clojure
(defcard dom-node-not-updating
  "Seems dom-node doesn't update?"
  (dom-node
    (fn [state node]
      (set! (.-innerHTML node) (str "Click me count: " (:count @state)))
      (set! (.-onclick node) #(swap! state update-in [:count] inc))))
  {:count 0}
  {:inspect-data true
   :watch-atom true})
```

I have tracked the problem down to `defonce-react-class DomComponent` here: https://github.com/bhauman/devcards/blob/d3a3000593e5b07827ebc98ffe152f1a6520b486/src/devcards/core.cljs#L314

AFAIK it does not make use of the `:data_atom` passed to it by `defn- dom-node*` here: https://github.com/bhauman/devcards/blob/d3a3000593e5b07827ebc98ffe152f1a6520b486/src/devcards/core.cljs#L498

I'm not react-able enough to fix this, sorry =[ 
(and therefore in great need of `dom-node` !)

**Comment by bhauman** [comment]
This is an interesting one. 
I'm wondering what the behavior should be. 

Here is a solution in the meantime

```
(def render  (fn [state node]
      (set! (.-innerHTML node) (str "Click me count: " (:count @state)))
      (set! (.-onclick node) #(swap! state update-in [:count] inc))))) 


(defcard dom-node-not-updating
  "Seems dom-node doesn't update?"
  (dom-node
    (fn [state node]
     (add-watch state :rendering (fn [_ _ _ _] (render state node)) ;; idempotent
     (render state node))
  {:count 0}
  {:inspect-data true})
```

**Comment by fdserr** [comment]
Thanks much, that should do the trick for now.

**Comment by exupero** [comment]
I ran into this too and came up with a similar solution, but I also notice that the history controls don't appear when the state changes. They only show up after I save the file and Figwheel reloads.

**Comment by bhauman** [comment]
good point, that makes sense
