### ISSUE TITLE
"This shouldn't work" testing example on addition

### ISSUE THREAD

**Issue by ricardojmendez** [bhauman/devcards#49]
On the test demos, the following example is used repeatedly:

```clojure
(is (= (+ 1 0 0 0) 1) "This shouldn't work")
```

Maybe I'm missing something and it's an example of what _should_ work, but why the label, and why is it used under "bad stuff" too?

**Comment by bhauman** [comment]
The wording is arbitrary, I'm sorry for the confusion. I will happily take a PR for any changes.

**Comment by ricardojmendez** [comment]
I solved this on pull request #55
