### ISSUE TITLE
Reagent component with input box loses focus on change when tracking atom

### ISSUE THREAD

**Issue by mathfarmer** [bhauman/devcards#52]
Having a lot of fun with devcards and figwheel, but ran into the following issue: if I add a reagent component with an input box that updates on change to a card and also try tracking the atom those changes flow to, the input box loses focus on every change, i.e. on every keystroke. [Gist to reproduce is here](https://gist.github.com/mathfarmer/17d8d57e2b384a86ecba).

Note that there is an easy enough workaround for this: duplicate the card, but don't pass the state atom to that one. The one without the atom accepts changes to the input box without losing focus just fine, and you still get the live state display and history tracking in the other card, which otherwise works just fine.

**Comment by bhauman** [comment]
Try adding :watch-atom false to the devcards options

**Comment by mathfarmer** [comment]
No effect.

**Comment by bhauman** [comment]
Hmmmm must be a bug ... I think that option is being ignored.

**Comment by bhauman** [comment]
I found the problem in Reagent:
https://github.com/reagent-project/reagent/issues/195

**Comment by bhauman** [comment]
and here is a new version of your gist fixed
https://gist.github.com/bhauman/24407865e5714c2e023a

**Comment by mathfarmer** [comment]
Cool! Thanks for tracking that down. I will track the upstream issue. Closing this one down.

Thanks again! Your tools really do make UI work pleasant.

**Comment by bhauman** [comment]
I was wrong about that I am fixing this in Devcards right now.

**Comment by bhauman** [comment]
This is fixed in the recent release of Devcards.
