### ISSUE TITLE
Devcards not auto-updating with figwheel

### ISSUE THREAD

**Issue by joakin** [bhauman/devcards#54]
Hi!

I'm trying to integrate devcards into an existing project. It works great, but the auto-loading with figwheel isn't working because it says i'm not requiring my files. Please, I would really appreciate some guidance.

```
Figwheel: NOT loading these files 
utils.cljs?rel=1444821373948:41 not required: ("/webkipedia/devcards/search.js")
```

This seems very weird, since the files are in fact required (same thing happens with the `:main` ns I've set in the config:

* `project.clj` where I specify a `:main webkipedia.devcards.core` [joakin/webkipedia/blob/devcards/project.clj#L31](https://github.com/joakin/webkipedia/blob/devcards/project.clj#L31) in the `devcards` build id.
* That main ns is here [src/webkipedia/devcards/core.cljs](https://github.com/joakin/webkipedia/blob/devcards/src/webkipedia/devcards/core.cljs)
* Which just includes this [src/webkipedia/devcards/search.cljs](https://github.com/joakin/webkipedia/blob/devcards/src/webkipedia/devcards/search.cljs)
* Changing either [src/webkipedia/devcards/core.cljs](https://github.com/joakin/webkipedia/blob/devcards/src/webkipedia/devcards/core.cljs) or [src/webkipedia/devcards/search.cljs](https://github.com/joakin/webkipedia/blob/devcards/src/webkipedia/devcards/search.cljs) will print in the console **`Figwheel: NOT loading these files, not required`** as I pasted above.

For running figwheel I'm doing `rlwrap lein figwheel devcards dev` so that I get both the app and the devcards compiled, and I open index.html and [cards.html](https://github.com/joakin/webkipedia/blob/devcards/resources/public/cards.html#L10) in the browser to get the live-reloading on both tabs.

I can't shake the feeling I'm doing something basic wrong, or misunderstanding how devcards should be set up. Any help would be appreciated. Feel free to [clone the repo with the devcards branch](https://github.com/joakin/webkipedia/tree/devcards) and try it out if you want to.

Thanks a lot for your work and the tools you create @bhauman, they are awesome :heart:

**Comment by bhauman** [comment]
I'm going to check this out this morning.

**Comment by bhauman** [comment]
I checked out your project and it seems to be working fine for me.  Are you on a windows platform?

For me on the `index.html` page you I see 
```
Figwheel: NOT loading these files 
utils.cljs?rel=1444838725147:38 not required: ("/webkipedia/devcards/search.js" nil)
This is expected.
```

But on the `cards.html` page I see things like
```
Figwheel: loaded these files
utils.cljs?rel=1444838260059:38 ("../webkipedia/devcards/search.js" "../webkipedia/devcards/core.js")
Figwheel: NOT loading these files 
utils.cljs?rel=1444838260059:38 not required: ("/webkipedia/state/logger.js" "/webkipedia/state/route.js" "/webkipedia/state/explore.js" "/webkipedia/api/core.js" "/webkipedia/ui/page_header.js" )
```
This is also expected.


This is because both builds are watching the same directories.
(It's probably better to put your cards on a separate watch path and then have :source-paths ["src" "cards_src])

From your statements it doesn't seem like this is happening to you and when you are on the `cards.html` page you are getting these
``` 
Figwheel: NOT loading these files 
utils.cljs?rel=1444838725147:38 not required: ("/webkipedia/devcards/search.js" nil) 
```
messages??
That doesn't seem right.

**Comment by joakin** [comment]
Hmmf, that is weird!

I've run only `lein figwheel devcards` and now when I update `search.cljs` (which was originally requested with `http://localhost:3449/js/compiled/devcards_out/webkipedia/devcards/search.js` get's requested as `http://localhost:3449/webkipedia/devcards/search.js?zx=8aryg1wka740` so it gives me a not found:

```
Figwheel: notified of file changes
jsloader.js:197 GET http://localhost:3449/webkipedia/devcards/search.js?zx=8aryg1wka740
utils.cljs?rel=1444821373948:40 Figwheel: Error loading file webkipedia/devcards/search.js
utils.cljs?rel=1444821373948:39 Figwheel: NOT loading these files 
utils.cljs?rel=1444821373948:41 not required: ("/webkipedia/devcards/search.js")
```

Not sure why but it's not using the prefix `/js/compiled/devcards_out`specified in `:asset-path "js/compiled/devcards_out"`.

Gonna keep digging and see if I figure it out.

The config: https://github.com/joakin/webkipedia/blob/devcards/project.clj#L27-L35

Am I supposed to write the devcards along with my code or separate? I've been looking at the examples and it seems like it would be better to interleave the code with the cards.

I'm going to test using the same `:main` entry and conditionally loading the app on `webkipedia.core` instead of putting everything on a different ns/entrypoint.

**Comment by joakin** [comment]
Sorry, I'm on OSX 10.10.3.

This are my steps exactly:

1. Run `lein figwheel devcards`
```
public (devcards *$=) $ rlwrap lein figwheel devcards
Figwheel: Starting server at http://localhost:3449
Focusing on build ids: devcards
Compiling "resources/public/js/compiled/webkipedia_devcards.js" from ["src"]...
Successfully compiled "resources/public/js/compiled/webkipedia_devcards.js" in 9.089 seconds.
Started Figwheel autobuilder
WARNING: unable to load "cemerick.piggieback/wrap-cljs-repl" middleware

Launching ClojureScript REPL for build: devcards
Figwheel Controls:
          (stop-autobuild)                ;; stops Figwheel autobuilder
          (start-autobuild [id ...])      ;; starts autobuilder focused on optional ids
          (switch-to-build id ...)        ;; switches autobuilder to different build
          (reset-autobuild)               ;; stops, cleans, and starts autobuilder
          (reload-config)                 ;; reloads build config and resets autobuild
          (build-once [id ...])           ;; builds source one time
          (clean-builds [id ..])          ;; deletes compiled cljs target files
          (fig-status)                    ;; displays current state of system
          (add-dep [org.om/om "0.8.1"]) ;; add a dependency. very experimental
  Switch REPL build focus:
          :cljs/quit                      ;; allows you to switch REPL to another build
    Docs: (doc function-name-here)
    Exit: Control+C or :cljs/quit
 Results: Stored in vars *1, *2, *3, *e holds last exception object
Prompt will show when figwheel connects to your application
To quit, type: :cljs/quit
cljs.user=>
```
2. Load http://localhost:3449/cards.html#!/webkipedia.devcards.search
3. 
```
Navigated to http://localhost:3449/cards.html
react-with-addons.inc.js:4486 Download the React DevTools for a better development experience: https://fb.me/react-devtools
utils.cljs?rel=1444821373948:39 Figwheel: trying to open cljs reload socket
utils.cljs?rel=1444821373948:39 Figwheel: socket connection established
react-with-addons.inc.js:21628 Warning: Each child in an array or iterator should have a unique "key" prop. Check the React.render call using <div>. See https://fb.me/react-warning-keys for more information.```
4. Edit `src/webkipedia/devcards/search.cljs` changing the markdown string.
5. Nothing changes on the browser. Open console and see:
```
utils.cljs?rel=1444821373948:39 Figwheel: notified of file changes
jsloader.js:197 GET http://localhost:3449/webkipedia/devcards/search.js?zx=q3qw6l88rb3 
utils.cljs?rel=1444821373948:40 Figwheel: Error loading file webkipedia/devcards/search.js
utils.cljs?rel=1444821373948:39 Figwheel: NOT loading these files 
utils.cljs?rel=1444821373948:41 not required: ("/webkipedia/devcards/search.js")
```

I see a warning when starting figwheel that I didn't notice about piggieback. I don't think it has anything to do but I'll get that fixed.

**Comment by joakin** [comment]
I've finally made a `lein clean` and now everything works fine... :disappointed: 

It's always a `lein clean`, noob mistake. Sorry to waste your time.

Do you have any thoughts (written somewhere maybe?) about where to put cards? Along with the code base? Separate?

Sorry again for the waste of time :(, and thanks again for the plugins, looking forward to developing with devcards!
