### ISSUE TITLE
devcards and reagent/create-class

### ISSUE THREAD

**Issue by rhacker** [bhauman/devcards#63]
Hi @bhauman, thanks for creating this nice plugin.

I'm working with some highcharts component and reagent for now. The project is pretty simple, it's almost the same as this one : https://github.com/reagent-project/reagent-cookbook/blob/master/recipes/highcharts/src/cljs/highcharts/core.cljs
What is the right way to use custom component ( with `reagent/create-class` ) with `defcard-rg` ?

Thanks

**Comment by bhauman** [comment]
I beleive you would do it like this:

```
(def mycomp (reagent/create-class ...))

(defcard-rg mycomponent-example
  [my-comp ...])
```

But I don't use reagent so you may want to ask around.

**Comment by rhacker** [comment]
thanks @bhauman . It works flawlessly :)
