### ISSUE TITLE
How to show cljs.test error messages for failed tests?

### ISSUE THREAD

**Issue by sp3ctum** [bhauman/devcards#68]
I'm liking the idea of devcards. :+1:  I wrote some simple tests with it, but unfortunately some of them failed.

From the devcard UI I don't see why they did, though. Is it possible to show the error messages like the cljs.test runner does it?

**Comment by bhauman** [comment]
Can you give me an example of what you are doing?

**Comment by sp3ctum** [comment]
Yeah, when a test fails I basically want to show an error message like the one here ![](https://camo.githubusercontent.com/064d7c9d774ef7cfce36e695f9d800becd05fd00/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f626861756d616e2d626c6f672d696d616765732f64657663617264732d616374696f6e2d73686f742e706e67)

But instead of the "Expected stuff to equal stuff" message I just get a red container showing the test body. My problem is I can't see the cause of the failure.

**Comment by sp3ctum** [comment]
Here is my test class (I'm writing a pong game)

```lisp
(ns pocpong.tests.engine-tests
  (:require [cljs.test :refer-macros [is] :include-macros true]
            [pocpong.engine.movement :as m]
            [pocpong.engine.types :as e])
  (:require-macros [devcards.core :as dc :refer [deftest]]))

(def include-dummy :yep)

(deftest move-ball-tests
  "positive Velocity"
  (is (= (e/Position. 6 6)
         (let [state (e/map->PongState
                      {:ball (e/Ball. (e/Position. 5 5)
                                      (e/velocity 1 1))})]
           (-> (m/move-ball state)
               :ball
               :position))))

  "negative Velocity"
  (is (= (e/Position. 4 4)
         (let [state (e/map->PongState
                      {:ball (e/Ball. (e/Position. 5 5)
                                      (e/velocity -1 -1))})]
           (-> (m/move-ball state)
               :ball
               :position)))))
```
