### ISSUE TITLE
[reagent] initial-data isn't IReactiveAtom

### ISSUE THREAD

**Issue by Frozenlock** [bhauman/devcards#90]
The initial-data passed to the Reagent components doesn't implement the `IReactiveAtom` protocol.

This makes some Reagent features, such as the [cursors](https://github.com/reagent-project/reagent/blob/6e8a73cba3a0fb13d3cf6dc38168e889bef9d337/src/reagent/ratom.cljs#L240), unusable in a component rendered with `devcards`.

**Comment by bhauman** [comment]
Frozenlock you are aware that you can pass a RAtom into a card as :initial-data like so?
https://github.com/bhauman/devcards/blob/master/example_src/devdemos/reagent.cljs#L215

You can even make it an ratom inline like so `(r/atom {:counter 0})`

But you are right, we could make sure that default initial-data is converted or initialized as an ratom here:
https://github.com/bhauman/devcards/blob/master/src/devcards/core.clj#L154

**Comment by Frozenlock** [comment]
I did not know! Thanks for the info.

This makes things much easier. Feel free to close this issue; using ratom as initial data solves pretty much everything.

---

I even just realized that the 3 example links from the readme point to particular namespaces and that a bunch of others (such as the one you linked) are [available](http://rigsomelight.com/devcards/#!/) if you click on the top devcard link.
