### ISSUE TITLE
ReactDOM.render is not defined

### ISSUE THREAD

**Issue by bago2k4** [bhauman/devcards#93]
Hi,
I have been using devcards for human tests in [this project](github.com/open-company/open-company-web) for a while and i have to say that i'm very happy with it.
The problem is that since version 0.2.1 it fails with this error:
```console
Uncaught TypeError: Cannot read property 'render' of undefined
   devcards$system$renderer @ system.cljs?rel=1453127706018:334
   (anonymous function) @ system.cljs?rel=1453127706018:467
```

The error happens at this line https://github.com/bhauman/devcards/blob/master/src/devcards/system.cljs#L334

If I check the js console i can see that ReactDOM is suggested by the auto completion but if I try to print out the value in the console it's undefined and ReactDOM.render is too.

Any suggestion of what may be causing this issue? How can i force ReactDOM to be included in the compiled js?

Thanks for this great tool!

**Comment by belucid** [comment]
FWIW, it works fine up to version: 0.2.0-8

Lein file is here: https://github.com/open-company/open-company-web/blob/mainline/project.clj

**Comment by bhauman** [comment]
It's really hard to know exactly what is happening here.
But perhaps an explicit :dependency on react and react-dom is in order?

**Comment by bhauman** [comment]
I looked at the commits and the only thing hat I think could cause this problem is this one
https://github.com/bhauman/devcards/commit/c1da65eced5c2a3c1bf7375d58924b397c645c7b
Bumping he sablono dep and explicitly requiring react is probably what is causing this.  No idea why.

Similar to #92

**Comment by bago2k4** [comment]
@bhauman i have added all the dependencies:
https://github.com/open-company/open-company-web/blob/devcards-fix/project.clj#L54-L57

also i have forced the require of those deps to make sure they are included but no luck:
https://github.com/open-company/open-company-web/blob/devcards-fix/src/open_company_web/lib/devcards.cljs#L12-L15

I also tried to move these dependencies to the main _:dependencies_ object instead of the _:devcards_ profile but the result is the same.

Any other idea/suggestion?

**Comment by bhauman** [comment]
Well I downloaded you project and it seems that you need to change this line
 [cljs-react-test "0.1.3-SNAPSHOT" :exclusions [cljsjs/react]] ; React test utilities 
to this
 [cljs-react-test "0.1.3-SNAPSHOT" :exclusions [cljsjs/react-with-addons]] ; React test utilities

**Comment by bago2k4** [comment]
@bhauman thanks, that worked! I'll update the my project with your suggestion.

**Comment by danielcompton** [comment]
I ran into this issue setting up devcards on a project that was using Reagent `0.5.1`. It might be worth making a note in the README that the latest version of Devcards requires React 14, which conflicts with Reagent versions lower than `0.6.0-alpha`?
